[project]
name = "neural-net-from-scratch"
version = "0.1.0"
description = "Building a neural network from scratch"
requires-python = ">=3.8"
readme = "README.md"
dependencies = [
    "numpy",
    "matplotlib",
]
